### ISSUE TITLE
NOT regarding This project Sorry

### ISSUE THREAD

**Issue by Abhishek-Manda1** [Anikin1610/Speech-Command-Recognition-Speaker-dependent-#1]
Hello anikin , Srry for bothering you but I have no means execpt this to contact you, again  I am very very srry .The reason I am writing you as i am very new to cocotb and want to learn it ,can you share your email so that we can talk .It will be very kind of you.
later I will delete this issue.
Thanks

**Comment by Anikin1610** [comment]
Hey, I'm just as new to cocotb as you are. But if you are having I'd be happy to try and help.
